# compile command:
# make -C /usr/src/kernels/2.6.35.6-45.fc14.i686 M=`pwd` modules
# /usr/src/kernels/2.6.35.6-45.fc14.i686 is the kernel source path in your PC
#
#
# make -C /usr/src/kernels/2.6.35.6-45.fc14.i686 M=`pwd` modules
#
#

obj-m := usb_leds.o


clean:
	rm -f *mod* *odule* *.o *.ko
